### PR TITLE
Added Typescript definitions

### PR DESCRIPTION
**Pull request by PragunSaini**
Here it is
#12

### CODE REVIEW

**Comment by PragunSaini** [comment]
Should I allow the close property of the options param of registerTag() function to be null? For self closing tags?

**Comment by Cherry** [comment]
Yes, that would be good. There's also a `replace` function that's not well documented, but can be seen in the `img` tag at https://github.com/nodecraft/ya-bbcode/blob/ed9bb0629b7af9b8088197966554fc7622ed90af/ya-bbcode.js#L113. It takes an `attr` as per open/close, but also includes `innerContent` as the second argument.

**Comment by PragunSaini** [comment]
Added `replace` and `ignore` types in registerTag method

**Comment by Cherry** [comment]
Awesome, thanks. Merged. I'll push a release shortly.

**Comment by Cherry** [comment]
Released in 1.0.12. 🎉 Let me know if you run into any issues - I don't use TypeScript frequently.

**Pull request merged**
